#!/usr/bin/env python


def configure(conf):
	pass


def build(bld):
	import os
	bld(
		features = ['c', bld.env['CLIBTYPE']],
		includes = ['.', '../..'],
		uselib = bld.env['COMMON_USELIB'],
		target = 'gstimxcommon',
		vnum = bld.env['GSTIMX_VERSION'],
		source = bld.path.ant_glob('*.c')
	)

